services:
  compile-service:
    image: ghcr.io/dangooding/koka-playground-compile-service:main

  runner-service:
    image: ghcr.io/dangooding/koka-playground-runner-service:main

  compile-and-run-service:
    image: ghcr.io/dangooding/koka-playground-compile-and-run-service:main

  proxy:
    image: ghcr.io/dangooding/koka-playground-proxy:main
    networks:
      common:
    ports:
      - "80:80"

networks:
  common:
    driver: overlay
