x-common-env-vars: &common-env-vars
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,env,prometheus"
  MANAGEMENT_ENDPOINT_ENV_SHOW_VALUES: "always"

services:
  compile-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: koka-playground-compile-service
      args:
        # use a locally built version of this image for local development
        # since the published registry version is amd64 only
        RUN_COMPILER_IMAGE: run-koka-compiler:latest
    environment:
      <<: *common-env-vars

  runner-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: koka-playground-runner-service
      args:
        RUN_COMPILER_IMAGE: run-koka-compiler:latest

    environment:
      <<: *common-env-vars

    security_opt:
      - seccomp:seccomp/bwrap-seccomp-profile.json

  compile-and-run-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: koka-playground-compile-and-run-service
    environment:
      COMPILE_AND_RUN_SERVICE_ALLOWED_WS_ORIGIN: "http://localhost"
      <<: *common-env-vars
    ports:
      - "80:80"

  prometheus:
    image:
      prom/prometheus:v3.4.2
    volumes:
      - prometheus-data:/prometheus
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      monitoring:

  grafana:
    image:
      grafana/grafana-oss:12.1.1
    volumes:
      - grafana-storage:/var/lib/grafana
    secrets:
      - grafana-admin-password
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: "/run/secrets/grafana-admin-password"
    networks:
      monitoring:
    ports:
      - "3000:3000"

volumes:
  prometheus-data:
  grafana-storage:

networks:
  common:
    driver: bridge

secrets:
  grafana-admin-password:
    file: metrics/grafana-admin-password.txt
