# this is a base file which the .prod/.dev files add to
services:
  compile-service:
    volumes:
      - exe-store:/etc/exe-store
    environment:
      # binds property local-exe-store.directory
      LOCALEXESTORE_DIRECTORY: "/etc/exe-store"
      DEBUG: "true"
      ORG_SPRINGFRAMEWORK_WEB_FILTER_COMMONSREQUESTLOGGINGFILTER: "DEBUG"
      LOGGING_LEVEL_ROOT: "debug"
    networks:
      common:

  runner-service:
    cap_add:
      - SYS_ADMIN
    # ideally we would set the seccomp profile just for this service,
    # however docker swarm doesn't support passing this option yet
    # so instead we set it at the daemon level.
    #    security_opt:
    #      - seccomp:bwrap-seccomp-profi~le.json
    volumes:
      - exe-store:/etc/exe-store
    environment:
      LOCALEXESTORE_DIRECTORY: "/etc/exe-store"
      DEBUG: "true"
      ORG_SPRINGFRAMEWORK_WEB_FILTER_COMMONSREQUESTLOGGINGFILTER: "DEBUG"
      LOGGING_LEVEL_ROOT: "debug"
    networks:
      common:

  compile-and-run-service:
    environment:
      COMPILE_SERVICE_HOSTNAME: "compile-service"
      RUNNER_SERVICE_HOSTNAME: "runner-service"
      DEBUG: "true"
      ORG_SPRINGFRAMEWORK_WEB_FILTER_COMMONSREQUESTLOGGINGFILTER: "DEBUG"
      LOGGING_LEVEL_ROOT: "debug"
    networks:
      common:

volumes:
  exe-store:
