x-common-env-vars: &common-env-vars
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,env,prometheus"
  MANAGEMENT_ENDPOINT_ENV_SHOW_VALUES: "always"

services:
  compile-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: koka-playground-compile-service
      args:
        # use a locally built version of this image for local development
        # since the published registry version is amd64 only
        RUN_COMPILER_IMAGE: run-koka-compiler:latest
    environment:
      <<: *common-env-vars

  exe-cache:
    build:
      context: .
      dockerfile: Dockerfile
      target: koka-playground-exe-cache

  runner-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: koka-playground-runner-service
      args:
        RUN_COMPILER_IMAGE: run-koka-compiler:latest

    environment:
      <<: *common-env-vars

    security_opt:
      - seccomp:seccomp/bwrap-seccomp-profile.json

  compile-and-run-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: koka-playground-compile-and-run-service
    environment:
      COMPILE_AND_RUN_SERVICE_ALLOWED_WS_ORIGIN: "http://localhost"
      <<: *common-env-vars
    ports:
      - "80:80"

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile
      target: koka-playground-prometheus
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    ports:
      - "3000:3000"

networks:
  common:
    driver: bridge
