services:
  compile-service:
    image: ghcr.io/dangooding/koka-playground-compile-service:main

  runner-service:
    image: ghcr.io/dangooding/koka-playground-runner-service:main

  compile-and-run-service:
    image: ghcr.io/dangooding/koka-playground-compile-and-run-service:main
    environment:
      COMPILE_AND_RUN_SERVICE_ALLOWED_WS_ORIGIN: "https://koka-zero.danielgooding.uk"

  proxy:
    image: ghcr.io/dangooding/koka-playground-proxy:main
    networks:
      common:
    environment:
      CERTBOT_EMAIL: "dan.gooding2000@gmail.com"
      DEBUG: 1
    volumes:
      - nginx_secrets:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

networks:
  common:
    driver: overlay

volumes:
  nginx_secrets: