# this is a base file which the .prod/.dev files add to

x-health-check: &healthcheck
  test:
    [ "CMD-SHELL",
      "wget -q -O - http://localhost/actuator/health | jq --exit-status '.status == \"UP\"' >/dev/null" ]

x-logging-env-vars: &logging-env-vars
  DEBUG: "true"
  ORG_SPRINGFRAMEWORK_WEB_FILTER_COMMONSREQUESTLOGGINGFILTER: "DEBUG"
  LOGGING_LEVEL_ROOT: "debug"

services:
  compile-service:
    volumes:
      - exe-store:/etc/exe-store
    environment:
      <<: *logging-env-vars
      # binds property local-exe-store.directory
      LOCALEXESTORE_DIRECTORY: "/etc/exe-store"
    networks:
      common:
    healthcheck: *healthcheck

  runner-service:
    # bwrap creates zombies, so need an init process to reap them
    init: true
    cap_add:
      - SYS_ADMIN
    # ideally we would set the seccomp profile just for this service,
    # however docker swarm doesn't support passing this option yet
    # so instead we set it at the daemon level.
    #    security_opt:
    #      - seccomp:bwrap-seccomp-profi~le.json
    volumes:
      - exe-store:/etc/exe-store
    environment:
      <<: *logging-env-vars
      LOCALEXESTORE_DIRECTORY: "/etc/exe-store"
    networks:
      common:
    healthcheck: *healthcheck

  compile-and-run-service:
    environment:
      <<: *logging-env-vars
      COMPILE_SERVICE_HOSTNAME: "compile-service"
      RUNNER_SERVICE_HOSTNAME: "runner-service"
    networks:
      common:
    healthcheck: *healthcheck

volumes:
  exe-store:
