services:
  compile-service:
    image: ghcr.io/dangooding/koka-playground-compile-service:main

  runner-service:
    image: ghcr.io/dangooding/koka-playground-runner-service:main

  compile-and-run-service:
    image: ghcr.io/dangooding/koka-playground-compile-and-run-service:main

networks:
  common:
    driver: overlay
